module.exports = {
    profissional: {
        idProfissional: 0,
        idUsuario: 0,
        nomeEmpresa: "",
        email: "",
        numeroContato: "",
        cidade: "",
        estado: "",
        enderecoComercial: "",
        numeroCPF: "",
        is_CNPJ: "",
        numeroCNPJ: "",
        descricaoEmpresa: "",
        categoria: "",
        segmento: "",
        valorMinimo: "",
        maisDeUmEventoPorDia: false,
        formasPagamento: "",
        trabalhaSozinho: false,
        nivelConta: 0,
        pontosAcumulados: 0,
        classificacao: 0.0,
        visitasVitrine: 0,
        orcamentosRecebidos: 0,
        casamentosBemSucedidos: 0,
        tokenConvite: "",
        is_CadastroPorConvite: false,
        idUsuarioConvite: 0
    },

    noiva: {
        idNoivos: 0,
        idUsuario: 0,
        nomeNoiv: "",
        Is_Noiva: true,
        email: "",
        numeroContato: "",
        cidade: "",
        estado: "",
        nomeConjuge: "",
        dataCasamento: "",
        idCasamento: 0,
        pontosAcumulados: 0,
        is_CadastroPorConvite: false,
        idUsuarioConvite: 0
    },

    casamento: {
        idCasamento: 0,
        dataCasamento: "",
        nomeNoivx: "",
        nomeConjuge: "",
        idNoiva: 0,
        luaMel: "",
        qtdConvidados: ""
    },

    dadosUsuarioEmpresaDTO: {
        idUsuario: "",
        nomeUsuario: "",
        email: "",
        senha: "",
        numeroContato: "",
        estado: "SP",
        enderecoComercial: "",
        categoria: "recepcao",
        segmento: "",
        is_CadastroPorConvite: false,
        idUsuarioConvite: null,
        tokenUsuarioConvite: 0
    },

    dadosUsuarioNoivDTO: {
        idUsuario: null,
        nomeUsuario: "",
        email: "",
        contato: "",
        senha: "",
        cidade: "",
        estado: "SP",
        is_Noiva: true,
        dataCasamento: "",
        is_CadastroPorConvite: false,
        idUsuarioConvite: null,
        tokenUsuarioConvite: null,
        isSimulacao: null,
        utm_source: "",
        utm_medium: "",
        utm_campaign: "",
        utm_id: "",
        utm_term: "",
        utm_content: "",
    },

    login: {
        user: '',
        password: ''
    },

    dadosResumoPerfilProfissionalDTO: {
        idUsuario: "",
        nomeUsuario: "",
        fotoPerfil: "",
        tipoUsuario: "",
        idProfissional: "",
        cidade: "",
        estado: "",
        enderecoComercial: "",
        nomeEmpresa: "",
        descricaoEmpresa: "",
        email: "",
        numeroContato: "",
        is_Whatsapp: "",
        numeroCPF: "",
        is_CNPJ: "",
        numeroCNPJ: "",
        nivelConta: "",
        tokenConvite: 0,
        valorMinimo: "",
        formasPagamento: "",
        maisDeUmEventoPorDia: false,
        trabalhaSozinho: false
    },

    dadosCadastroRelatorio: {
        id_profissional: "",
        nome_usuario: "",
        email: "",
        data_criacao: "",
        numero_contato: "",
        numero_contato_formatado: "",
        nome_empresa: "",
        estado: ""
    }
}
